language: python
python:
  - 3.9

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt 

script:
  - python -m unittest test/dataset_test.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$pypi-AgEIcHlwaS5vcmcCJDE1NzViMDBjLTA2NjEtNGY2Ny1iNTM0LTg5MmRkM2YyYjc4YwACGFsxLFsiYWRhcHRpdmUtZGF0YXNldCJdXQACLFsyLFsiNDJlNzc3NzItNGZjNS00MThiLTg0NzUtZGIwMTQ0Zjc2ZjAxIl1dAAAGICeM0OlOroZ63KxDbTN0ECor0L_N3iTAYWgrp8rnkuNd"
  on:
    branch: main