language: python
python:
- 3.9
before_install:
- python --version
- pip install -U pip
install:
- pip install -r requirements.txt
script:
- python -m unittest test/dataset_test.py
deploy:
  provider: pypi
  username: __token__
  password:
    secure: "cz72h0ohAVm5zkq2ohZvWANNPUMY4C0jTUlgxg2RTAVEOLVlaoEv0vcL1jhhm+HcMM+41pZyXs72zEevEae3Aqoa1CVm3Ad55IXHORIhOQXOD0LqVHs1vxdwVwWf2tsPT+rIK5Gb28fIwAs/uCYQN6PXPofuga7D1Y1GKnqMkhGwMZbJ5dKAYZh72tuL7JJmmQNjv6k9OmF5S+AGUY8cBLHZrjh4DVxap7vmrAvEfFyAPIy7RaUsAf3V6HlxUlK2W+k375KdbSkq46k1PbZL4uneHvcpy2apMkRX0AtHrczVOFre86CQ1gmuyBLiSO2orAl5TD3azWTwHRK1ybh+utX/hyL1B9ciISjjc0wrkC0WL24e49Pa+n6qpmeGo1jNLNXNHO/yiRGg6+U4Mx0W1B5dnwjVe8pCWjjNx/apd5KKGtITTHWkcXt7R4Byqi0nYKKQd6R03E3oxrwCOuzFLK3Cf1yWJ0JUdg3yEJ3z7UTp2l68G47kA8vKUJGHL4DChqkZm6T8xUfCsFNS98HiKf1aTrs5SqenZhti7DEdVkUXqp+dYrMJvj6dc4PaB9edu2Ene3m1yOCgGkQaaORBO+pZbYC47r4We6Q4qQ1xxggHH0bK0KzMsGLvQbxoXyOda6+QWcKmKY0wxd9TFQFbIkamtT0gfHbhgBb9KZcmKVU="
  on:
    branch: main
